name: Test build extension on Postgres
on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: postgres:latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install build essentials tools
        run: apt-get update && apt-get install -y build-essential

      - name: Build extension
        run: make install
      
      - name: Create extension in db
        run: sleep 45s;PGHOST=$(cat /etc/hostname) ;psql -h $PGHOST -p 5432 -U postgres postgres -c "create extension town;"