name: Test build extension on Postgres
on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: postgres:latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install build essentials tools
        run: apt-get update && apt-get install -y build-essential

      - name: Build extension
        run: make install

      - name: Wait 10 seconds
        run: sleep 10s
      
      - name: Create extension in db
        run: PGHOST=$(cat /etc/hostname) ;psql -h $PGHOST -p 5432 -U postgres postgres -c "create extension town;"